import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@Entity(primaryKeys: ['id','name'])
class Stats {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  
  final int id;
  final int month;
  final int score;

  //Default constructor
  Stats(
    this.id,
    this.score,
    this.month,
    //this.month
  );
}