import 'package:floor/floor.dart';
import 'package:intl/intl.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Steps {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final DateTime dateTime ;
  final int? value;
  //final int month;

  //Default constructor
  Steps(
    this.id,
    this.dateTime,
    this.value,
    //this.month
  );
/*
  Steps.fromJson(this.id, String date, Map<String, dynamic> json)
    : dateTime = DateFormat('yyyy-MM-dd HH:MM:ss').parse('$date${json["time"]}'),
      value = int.parse(json["value"]);
      */
}